version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13.13.0

commands:
  install_dependencies:
    description: Installs dependencies for project
    steps:
      - run:
          name: Install dependencies
          command: |
            cd node-tsc
            npm install

  run_linter:
    description: Runs linter on code
    steps:
      - run:
          name: Lint
          command: |
            cd node-tsc
            npm run lint

  run_unit_tests:
    description: Runs unit tests
    steps:
      - run:
          name: Run unit tests
          command: |
            cd node-tsc
            npm test
  setup_test_integ_env:
    description: Set up environment for integrtion test
    steps:
      - run:
          name: Setting up environment for integrtion test
          command: |
            cd ~
            mkdir test-box
            cd project/node-tsc
            npm run build && npm pack
            echo $PWD
            mv node-ts-cli-1.0.0.tgz ~/test-box
            cd ~/test-box/
            sudo npm install -g node-ts-cli-1.0.0.tgz 

jobs:
  build_branch:
    executor: node
    description: Builds, lints and lints code
    steps:
      - checkout
      - install_dependencies
      - run_linter
      - run_unit_tests
    
  publish_package:
    executor: node
    steps:
      - run:
          name: Testing publish
          command: |
            echo "Publish package in npm repositories"
            echo "Checking current working directory"
            pwd

  build_test_env:
    executor: node
    description: Runs set up environment for integrtion test
    steps:
      - checkout
      - install_dependencies
      - setup_test_integ_env

workflows:
  version: 2

  build_and_test:
    jobs:
      - build_branch:
          filters:
            branches:
              only: /.*/
      - build_test_env:
          filters:
            branches:
              only: /.*/
              
      - publish_package:
          filters:
            branches:
              only: master
          
