version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13.13.0

commands:
  install_dependencies:
    description: Installs dependencies for project
    steps:
      - run:
          name: Install dependencies
          command: |
            cd node-tsc
            npm install
  run_linter:
    description: Runs linter on code
    steps:
      - run:
          name: Lint
          command: |
            cd node-tsc
            npm run lint
  run_unit_tests:
    description: Runs unit tests
    steps:
      - run:
          name: Run unit tests
          command: |
            cd node-tsc
            npm test
  setup_integration_test_env:
    description: Set up environment for integration test
    steps:
      - run:
          name: Setting up environment for integration test
          command: |
            cd ~
            mkdir test-box
            cd project/node-tsc
            npm run build && npm pack
            mv node-ts-cli-1.0.0.tgz ~/test-box
            cd ~/test-box/
            sudo npm install -g node-ts-cli-1.0.0.tgz
            node-tsc .
  run_integration_test:
    description: Run integration test
    steps:
      - run:
          name: Runs integration test
          command: |
            cd ~ 
            cd project/integration-tests
            npm install
            npm test  
            
  second_integration_test_env:
    description: Set up second environment for integration test
    steps:
      - run:
          name: Setting up second environment for integration test
          command: |
            cd ~
            mkdir test-box-2
            cd project/node-tsc
            npm run build && npm pack
            mv node-ts-cli-1.0.0.tgz ~/test-box-2
            cd ~/test-box-2/
            sudo npm install -g node-ts-cli-1.0.0.tgz
            node-tsc my-test-project
jobs:
  lint-and-unit-tests:
    executor: node
    description: Builds, lints and tests code
    steps:
      - checkout
      - install_dependencies
      - run_linter
      - run_unit_tests

  integration-tests:
    executor: node
    description: Sets up environment for integration test and runs it
    steps:
      - checkout
      - install_dependencies
      - setup_integration_test_env
      - run_integration_test
  
  second-ingegration-test:
    executor: node
    description: Sets up second environment for integration test
    steps:
      - checkout
      - install_dependencies
      - second_integration_test_env

workflows:
  version: 2

  build-and-test:
    jobs:
      - lint-and-unit-tests:
          filters:
            branches:
              only: /.*/
      - integration-tests:
          filters:
            branches:
              only: /.*/
          requires:
            - lint-and-unit-tests
      - second-ingegration-test:
          filters:
            branches:
              only: /.*/
          requires:
            - lint-and-unit-tests